name: deploy_flutter_web

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/flutter-pages.yml'
      - 'lightguard_app/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - name: Install dependencies
        run: flutter pub get
        working-directory: lightguard_app
      - name: Build web
        run: flutter build web --release --base-href /
        working-directory: lightguard_app
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./lightguard_app/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
